version: '2'
services:
    sigterra_web-mysql:
        container_name: sigterra_web-mysql
        image: mysql:5.7.13
        # volumes:
        #     - ~/volumes/jhipster/sigterra_web/mysql/:/var/lib/mysql/
        environment:
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=sigterra_web
        ports:
            - 3306:3306
        command: mysqld --lower_case_table_names=1 --skip-ssl
